# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://slavi-galabov.github.io/
baseurl: /
title: Slavi Galabov
author: Slavi Galabov
description: Personal page
avatar: avatar.jpeg
email: slavi.galabov@gmail.com
github: slavi-galabov # username
linkedin: slavigalabov
stackoverflow: users/2352543/slavi-galabov   
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-72322657-1


# needed for travis-ci build
exclude: [vendor]
